### ISSUE TITLE
Where can i find the release apk for MeshCentralAndroidAgent

### ISSUE THREAD

**Issue by senolkehya** [Ylianst/MeshCentralAndroidAgent#1]
Hi Ylianst,
I want to install the apk for MeshCentralAndroidAgent to my mobile phone. I'm member of https://meshcentral.com/ . I create a Device Groups "Android" to my account. Can you please tell me the where can i find the apk.
If it is not possible https://meshcentral.com i will install the meshcentral to my private cloud server.
Seeing the AndroidAgent in meshcentral is really nice. I will be waiting your good news.
Thanks

**Comment by Ylianst** [comment]
Hi. You are too early. Once the server is updated to support the new agent, I will send out the APK. It's not possible to try now because the server does not support it. I will send out the APK as soon as possible.

**Comment by Ylianst** [comment]
MeshCentral Agent for Android is now on [Google Play Store here](https://play.google.com/store/apps/details?id=com.meshcentral.agent2). You can also get the [APK directly from the MeshCentral.com download page](https://meshcentral.com/info/downloads.html), look for "Mobile Downloads" on the right.

MeshCentral v0.7.48 or better is required to make the Android agent work.

Hope that helps - Ylian

**Comment by Ylianst** [comment]
MeshCentral.com is now updated and supports the Android agent. If you have any other issues, please open another issue here. Thanks.
