### ISSUE TITLE
Latest Android agent stops working

### ISSUE THREAD

**Issue by Mfinadmin** [Ylianst/MeshCentralAndroidAgent#10]
Dear @Ylianst 

Latest android agent is not working in many Android mobiles. Application stops working while configure the server through QR scanner / while click on connect button. 

I have tested the same in Samsung , Redme , Real me & Vivo phones. 

Android version - 10,9

**Comment by Ylianst** [comment]
Thanks for reporting this. Looking into it.

**Comment by Ylianst** [comment]
Ok, Google Play is reporting a lot of the same crash on the latest version, I am working on a fix.

**Comment by Ylianst** [comment]
Just published MeshAgent for Android v1.0.11 on Google Play (will be online once approved). I am not sure if it will fix it or not. APK available now on [MeshCentral.com](https://meshcentral.com/info/downloads.html).

**Comment by Mfinadmin** [comment]
Dear Ylianst 
Downloaded latest apk from meshCentral but not working...

**Comment by Ylianst** [comment]
Oh dear... that is not good. I will try on a different device I have.

**Comment by Ylianst** [comment]
I think I know what the problem is. Will have a new APK in a few minutes...

**Comment by Ylianst** [comment]
Ok, new APK on [MeshCentral.com](https://meshcentral.com/info/downloads.html). I was trying to save space, but the smaller APK is causing the problem. This APK will be bigger, but hopefully will work.

**Comment by Ylianst** [comment]
I see the problem now on my device and this new APK works for me.

**Comment by VINISHVV** [comment]
@Ylianst - confirmed,  the new API is working for me....

**Comment by Ylianst** [comment]
Thanks! I am working to see if I can make it small and work at the same time.

**Comment by Ylianst** [comment]
Ok. I just put a new APK, it is 4.7M instead of 6.7M. So smaller, and should still work.

**Comment by VINISHVV** [comment]
Wow !!!.

Now its working fine.....

**Comment by Mfinadmin** [comment]
@Ylianst 
Thanks new agent working fine....
