### ISSUE TITLE
Not on the store anymore

### ISSUE THREAD

**Issue by energywave** [Ylianst/MeshCentralAndroidAgent#19]
This app is not on the Play Store anymore

**Comment by jesta192** [comment]
Wow, I'm just jumping into MeshCentral and I noticed the same 😆...

**Comment by Astorek86** [comment]
Altough I don't have an Android-Device anymore, but it seems that the Agent is still reachable on the typical GooglePlay-Site:

https://play.google.com/store/apps/details?id=com.meshcentral.agent2

**Comment by energywave** [comment]
> Altough I don't have an Android-Device anymore, but it seems that the Agent is still reachable on the typical GooglePlay-Site:

Yes! Now it is! But I ensure it was not 3 days ago when I opened the issue. Something changed in the meanwhile. And I've seen that in the latest update (1.1.4) they've included the apk in the web ui add device dialog. Great! I close the issue.
