### ISSUE TITLE
Sideloading APK fails on Android 6.0.1

### ISSUE THREAD

**Issue by Jamesso** [Ylianst/MeshCentralAndroidAgent#2]
I downloaded the APK from [here](https://info.meshcentral.com/downloads/MeshCentral2/meshcentral-agent.apk) and tried to install on my Android 6.0.1 tablet.

This is the error I receive:
`Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]`

**Comment by Ylianst** [comment]
OK, will take a look. I think I have to sign the APK will the older signature style...

**Comment by Ylianst** [comment]
Just updated the APK on the download page to v1.0.1 with many improvements and using the older signature system, it's on the [download page now.](https://meshcentral.com/info/downloads.html) Let me know if that works.

**Comment by Jamesso** [comment]
Confirmed working. Thanks.
