### ISSUE TITLE
MeshCentral Agent stucks at Authenticating

### ISSUE THREAD

**Issue by v3DJG6GL** [Ylianst/MeshCentralAndroidAgent#20]
Hey all :)
First, thanks for this amazing tool!
I just deployed it on my own server behind Traefik reverse proxy. And so far, everything works great!

Only with the Android app I do have some issues:

- The apk versions directly from https://meshcentral.com/android/meshcentral-agent.apk and that one which I can download directly from the invite page are somewhat no installable. I tried it on two phones: On a Fairphone 5 with Android 12 and a Fairphone 3 with LineageOS 20 (idoéOS fork):
On both phones, Android throws the error `App not installed as package appears to be invalid.`

- The installation via _Google Play Store_ (or in my case _Aurora Store_) works. But as soon as I scan the QR code and try to establish a connection, the app gets stuck on `Authenticating`
  - On the server-side, I do get the following logs:
  `New agent at 192.168.20.87:57348
  Verified agent connection to <redacted> (192.168.20.87:57348).`
  - And then, some minutes later:
  `Soft disconnect <redacted> (192.168.20.87:57348)`

Since all other connections from windows computers (remote and local ones) are working flawlessly, I don't know what could cause the error here...

**Environment:**

- MeshCentral: v1.1.15
- MeshCentral Agent: v1.0.17

**Comment by jrf280** [comment]
Same problem but for now only with Android 13 (Samsung Tab S6 Lite and Xiaomi Redmi Note 10S)

On Android 12 it works perfectly. (Lenovo tab m10 3 gen and Xiaomi Redmi Note 9 Pro)


**Environment:**

MeshCentral: v1.1.16
MeshCentral Agent: v1.0.17

**Comment by si458** [comment]
OMG THANK YOU! 
just built the app here and tried it on my Z fold 3 and it works!!!
will get @Ylianst to try build and publish a new build ASAP
