### ISSUE TITLE
Android apk seems to be invalid if downloaded from invite link and meshcentral.com

### ISSUE THREAD

**Issue by v3DJG6GL** [Ylianst/MeshCentralAndroidAgent#22]
I have already mentioned this at #20. But since #20 was mainly another issue, I thought I might start a separate issue for that.

1. The apk versions directly from https://meshcentral.com/android/meshcentral-agent.apk and that one which I can download directly from the invite page are somewhat no installable. I tried it on two phones: On a Fairphone 5 with Android 12 and a Fairphone 3 with LineageOS 20 (idoéOS fork):
On both phones, Android throws the error `App not installed as package appears to be invalid`.

I just tried it now once again, the issue seems to be the same as two days ago.

Environment:

1. Meshcentral: v1.1.16
2. Phone 1: Fairphone 5, Android 12 (stock OS)
3. Phone 2: Fairphone 3, iodéOS v4.6 (forked LineageOS 20, which is based on Android 12)

**Comment by si458** [comment]
i will get @Ylianst to look into creating new APKs for us,
i know the was a BUG with an old APK which i think might be the one thats included in the web UI/invite links
can you try installing the app from the app store? does that install ok?

**Comment by v3DJG6GL** [comment]
I've been using the MeshAgent app from the Google Play Store for the last couple months without any issues. The issue is definitely related to the this specific apk version on the MeshCentral server.

**Comment by si458** [comment]
If I remember, the apk that's on the website and in the webui is an old version which supports less than Android 12, where as the one on the playstore had to now be built using android 12 or above,
I will get the latest apk version from @Ylianst and let u have it then u can see if the apk works and if so then I'll update it on the website and in the Web ui

**Comment by marclaporte** [comment]
@v3DJG6GL @si458 Any news on this?

**Comment by v3DJG6GL** [comment]
The issue seems solved.
The apk from the meshcentral server seems to be updated (1.0.21) :)
