### ISSUE TITLE
erorr when installing Agent from Google Play via Intune

### ISSUE THREAD

**Issue by wireks** [Ylianst/MeshCentralAndroidAgent#23]
On Lenovo TB-X606 i want to install Agent via Intune i`m receving error:

The application can’t be installed because it is incompatible with the device. (0xC7D24FBC)

**Comment by si458** [comment]
What Android version are you using?
I think @Ylianst had to update the apk so it needs a min of version 12 now...

**Comment by wireks** [comment]
Android 10

**Comment by si458** [comment]
the new requirement to install it from the google play store is set as 12 at the moment, im not sure if he can lower it or not
BUT you can always install the APK thats in the webui which is an old version which has a min requirement of 6 i believe

**Comment by wireks** [comment]
i saw that in store agent required android 12 so i tried to install from apk file via Intune

**Comment by si458** [comment]
> i saw that in store agent required android 12 so i tried to install from apk file via Intune

ok and did that work?
what APK did you use?
have you tried the one from the website instead? https://meshcentral.com/downloads

**Comment by wireks** [comment]
i tried apk from ui and from website  - no changes

**Comment by si458** [comment]
i dont sadly use intune so i have no idea but does this link help? https://github.com/MicrosoftDocs/IntuneDocs/issues/3002

**Comment by wireks** [comment]
1.0.20 Works!

**Comment by si458** [comment]
great! the is also a 1.0.21 update due soon too as the was a bug with old android and push notifications!
