### ISSUE TITLE
MeshCentral Agent not working on Android 14

### ISSUE THREAD

**Issue by dr-tennant** [Ylianst/MeshCentralAndroidAgent#28]
Hello everybody,

I am currently experiencing that the awesome MeshCentral Agent for Android crashes, when used on Android 14 devices. I can setup a server in the app, everything is fine. I can click on connect and see the device in MeshCentral, everything is fine. I try to access the desktop, allow everything on my phones and the app crashes. This occours on a Google Pixel 6 Pro running Android 14 as well as a Samsung A54 running Android 14. Devices running Android 13 are working perfectly fine with my server.

Is this behaviour known and maybe a bugfix rising somewhere, or is there any special trick or workaround I was unable to find?

Thanks in advance and best regards :-)

**Comment by ScubyG** [comment]
I've had the same issue last time I tried to use MC on my Pixel 6 Pro, I thought it might have been due to running Android 14 veesion of GrapheneOS so would be interested to see other replies on the issue, I will try it again and did in to the error logs

**Comment by si458** [comment]
Duplicate of #24 
Android 14 requires more permissions, so it currently just crashes, we have uploaded a new version to Google play and awaiting for them to approve it
In the mean time, you can build the app urself and generate an apk and install that, as the fix has already been implemented

**Comment by ScubyG** [comment]
> Duplicate of #24 
> Android 14 requires more permissions, so it currently just crashes, we have uploaded a new version to Google play and awaiting for them to approve it
> In the mean time, you can build the app urself and generate an apk and install that, as the fix has already been implemented 

Thank you, I'm going to build the app now

**Comment by dr-tennant** [comment]
Thanks, that worked perfectly fine for me. :-)

**Comment by si458** [comment]
No worries, glad it works.
I will do a build myself soon, and also target older versions of android (as currently it needs 12=>) and update the apk file on the website and inside meshcentral, until Google play nice and release the update!

**Comment by ScubyG** [comment]
works my end too
