### ISSUE TITLE
1.0.20 version in Play Store

### ISSUE THREAD

**Issue by wireks** [Ylianst/MeshCentralAndroidAgent#32]
Hi, i see that on GitHub we have 1.0.20 version of Android Agent but in Google Store is still 1.0.15 version. Can we update it ?

**Comment by si458** [comment]
We have already submitted it to Google but still awaiting for them to approve it...

**Comment by si458** [comment]
Update has been release on the play store for u to try :)
Should now also support Android 6-12 again!

**Comment by wireks** [comment]
Yeah it works!

**Comment by si458** [comment]
great! the is also a 1.0.21 update due soon too as the was a bug with old android and push notifications!
