### ISSUE TITLE
FEATURE REQUEST: Location Data

### ISSUE THREAD

**Issue by jtfeatures** [Ylianst/MeshCentralAndroidAgent#34]
I have read everything I can and I see that this was never implemented (in an automated way).  This is a huge deal for me and I want to help but I am still in the VERY early stages of learning programming and this beautiful program is far above me.  But, I wrote a PowerShell program that reports the devices location every 3 seconds and I would live to add that to the meshcentral installer so that the device (at least windows for now) will report its location or at least a close location with IP decoding if the GPS is not implemented.  How can I/We help get this option implemented?

**Comment by si458** [comment]
are u talking about location data in the android app? as android cant run powershell.
also this is the android app repo, not the windows agent
but you can already run `location` in the console tab of a device and it uses `ipinfo.io` to get details about the ip and location and returns a JSON value for you

**Comment by jtfeatures** [comment]
Dang it... Sorry about that.
