### ISSUE TITLE
Agent on x86 Android device and Android 11

### ISSUE THREAD

**Issue by henrylausd** [Ylianst/MeshCentralAndroidAgent#5]
Is this Agent built to also run on Android devices with x86 chipset, or is this for ARM only?

Will this Agent run on Android 11?

Thanks

**Comment by Ylianst** [comment]
The agent is built in the Android Studio with Kotlin and has no "native c" code in it. I am guessing it's not compiled for any specific CPU and so should work for both ARM and x86. If someone can confirm this, that would be great.

The Android app targets a minimum of SDK 23, which look like [Android 6.0 Marshmallow and after](https://source.android.com/setup/start/build-numbers). So yes, Android 11 (SDK 30) should work.
