### ISSUE TITLE
Remote Control Feature

### ISSUE THREAD

**Issue by senolkehya** [Ylianst/MeshCentralAndroidAgent#8]
Hi Ylianst,
I can make remote control to my android phone and samsung galaxy tab a7. I can see the secreen. But i can't click shortcuts.
Will you be add fully manage a remote android device? For example i want to unlock, open some applications etc.
IF you can develop we will be happy.
Thanks

**Comment by Ylianst** [comment]
Sadly, Android OS does not allow this. It is not possible. You can only view, not control.
